stages:
  ingest:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
      - data/external/train.csv
    outs:
      - data/raw/:
          persist: true

  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/
      - data/external/store.csv
    outs:
      - data/processed/processed_sales.csv