stages:
  ingest:
    cmd: python src/ingestion.py
    deps:
      - src/ingestion.py
    outs:
      - data/raw.csv:
          persist: true

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw.csv
    outs:
      - data/processed.csv
  
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed.csv
    outs:
      - models/xgboost_model.json